#index:
 #  path: /
  # controller: App\Controller\HomeController::index

#register:
 #  path: /register
  # controller: App\Controller\RegistrationController::register


#app_register:
 #  path: /register
  # controller: App\Controller\RegistrationController::register


#password:
   #path: /reset-password
  # controller: App\Controller\ResetPasswordController::request

#app_verify_email:
 #  path: '/verify/email'
  # controller: 'App\Controller\RegistrationController::verifyUserEmail'


#app_login:
 #  path: /login
  # controller: App\Controller\SecurityController::login

#app_logout:
 #  path: /logout
  # controller: App\Controller\SecurityController::logout


#home:
 # path: /home
  #controller: App/Controller/HomeController::index


#app_reset_password_request:
  # path: /reset-password
 #  controller: App\Controller\ResetPasswordController::request

#app_reset_password:
  # path: /reset-password/{token}
 #  controller: App\Controller\ResetPasswordController::reset

#app_home:
 #  path: /
 #  controller: App\Controller\HomeController::index

#app_check_email:
   #path: /verify-email
   #controller: App\Controller\VerificationController::verifyEmail
   #methods: ['GET']