#index:
#    path: /
#    controller: App\Controller\DefaultController::index


app_user_delete:
  path: '/user/{id}/delete'
  controller: 'App\Controller\UserController::delete'
  methods: [POST, DELETE]



user:
  path: /user
  controller: App\Controller\UserController::index




edit:
  path: /edit/{id}
  controller: App\Controller\ProfileController::editUser




home:
  path: /
  controller: App\Controller\HomeController::index

#app_user_edit:
 # path: '/user/edituser'
  #controller: 'App\Controller\UserController::edituser'
  #methods: [POST, EDIT]

logout:
  path: '/logout'

forget:
  path: /
  controller: App\Controller\SecurityController::forgetPassword
